{
 "title": "CLATAM 2018 - CPSE",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "type": "text", "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 }, "content": "# ASR-1" },
  { "type": "text", "gridPos": { "h": 4, "w": 11, "x": 11, "y": 0 }, "content": "# *ASR-02" },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 }, "content": "### UX Metrics\n#### Wireless" },
  {
   "title": "UX Ping Response",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "UX_PING",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ux_ping_ms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Agg IN from CUN",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Packets",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "flowdir", "operator": "=", "value": "IN" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "ASR-1-CANCUN" }
     ]
    }
   ]
  },
  {
   "title": "Agg OUT to CUN",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Packets",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "flowdir", "operator": "=", "value": "OUT" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "ASR-1-CANCUN" }
     ]
    }
   ]
  },
  {
   "title": "OUT to CANCUN",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "alias": "IN_CUN",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bits-Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "ASR-1-CANCUN" },
      { "condition": "AND", "key": "flowdir", "operator": "=", "value": "OUT" }
     ]
    }
   ]
  },
  {
   "title": "IN from CANCUN",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "alias": "IN_CUN",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bits-Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "ASR-1-CANCUN" },
      { "condition": "AND", "key": "flowdir", "operator": "=", "value": "IN" }
     ]
    }
   ]
  },
  {
   "title": "Agg IN from PLAYA",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Agreggate",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "flowdir", "operator": "=", "value": "IN" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "ASR-2-PLAYA" }
     ]
    }
   ]
  },
  {
   "title": "Agg OUT to PLAYA",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Agreggate",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "flowdir", "operator": "=", "value": "OUT" },
      { "condition": "AND", "key": "hostname", "operator": "=", "value": "ASR-2-PLAYA" }
     ]
    }
   ]
  },
  {
   "title": "OUT  to PLAYA",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "alias": "Outgoing_PLAYA",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bits-Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "ASR-2-PLAYA" },
      { "condition": "AND", "key": "flowdir", "operator": "=", "value": "OUT" }
     ]
    }
   ]
  },
  {
   "title": "IN from PLAYA",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 4 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "alias": "Incoming_PLAYA",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bits-Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "ASR-2-PLAYA" },
      { "condition": "AND", "key": "flowdir", "operator": "=", "value": "IN" }
     ]
    }
   ]
  },
  {
   "title": "UX Down",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 5 },
   "format": "Mbits",
   "valueName": "avg",
   "targets": [
    {
     "alias": "UX_DOWN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ux_download_mbps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "UX_WIRELESS_TESTER" }
     ]
    }
   ]
  },
  {
   "title": "UX Upload",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 7 },
   "format": "Mbits",
   "valueName": "current",
   "targets": [
    {
     "alias": "UX_PING",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ux_upload_mbps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "UX_WIRELESS_TESTER" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Rate (bits/secs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Incoming",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bits-Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "outside" },
      { "condition": "AND", "key": "flowdir", "operator": "=", "value": "IN" }
     ]
    },
    {
     "alias": "Outgoing",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bits-Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "outside" },
      { "condition": "AND", "key": "flowdir", "operator": "=", "value": "OUT" }
     ]
    }
   ]
  },
  {
   "title": "Traffic Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Incoming",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bits-Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "ASR-2-PLAYA" },
      { "condition": "AND", "key": "flowdir", "operator": "=", "value": "IN" }
     ]
    },
    {
     "alias": "Outgoing",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "bits-Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "ASR-2-PLAYA" },
      { "condition": "AND", "key": "flowdir", "operator": "=", "value": "OUT" }
     ]
    }
   ]
  },
  {
   "title": "UX INDEX WIFI",
   "type": "singlestat",
   "description": "User Experience  Perception Index\n# Wireless in Real Life Conditions:\n    # 802.11b MAX 6mbps Downstream\n    # 802.11g MAX 20Mbps Downstream\n    # 802.11n MAX 100Mbps Downstream\n    # 802.11ac MAX 200Mbps Downstream\n    # Formulae:\n    # SpeedTest Download / Wireless Index <= 1",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "alias": "UX_INDEX",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ux_index",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "UX_WIRELESS_TESTER" }
     ]
    }
   ]
  },
  {
   "title": "Traffic (packets/sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "Incoming",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pkts-Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flowdir", "operator": "=", "value": "IN" }
     ]
    },
    {
     "alias": "Outgoing",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pkts-Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flowdir", "operator": "=", "value": "OUT" }
     ]
    }
   ]
  },
  {
   "title": "Traffic (packets/sec)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 15 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "Incoming",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pkts-Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "ASR-2-PLAYA" },
      { "condition": "AND", "key": "flowdir", "operator": "=", "value": "IN" }
     ]
    },
    {
     "alias": "Outgoing",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pkts-Rate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=", "value": "ASR-2-PLAYA" },
      { "condition": "AND", "key": "flowdir", "operator": "=", "value": "OUT" }
     ]
    }
   ]
  }
 ]
}